### ISSUE TITLE
Clean up config

### ISSUE THREAD

**Issue by devonzuegel** [devonzuegel/clarity#117]
**Goal:** Make source entry extremely simple

**Current problems:**
- [x] using `process.env` directly, should instead load from `dotenv`
- [ ] frontend does not handle any injected environment-specific variables
- [ ] config is splattered all around the root `/server` and `/frontend` directories
