### ISSUE TITLE
Route posts under `/@:username/:pretty-post-id`

### ISSUE THREAD

**Issue by devonzuegel** [devonzuegel/clarity#202]
Currently, posts are routed under `/posts/:post-id`, which has a host of aesthetic and practical problems.

Also, allow the user to choose their `pretty-post-id`. Things to be careful of:
- [x] Validate the shit out of the user-chosen `pretty-post-id` (no spaces, for example)
- [x] `pretty-post-id`s must be unique by user AND post
     - `john` can have a post with id `hello-world` (permalink becomes `/@john/hello-world`), and so can `devon` (permalink becomes `/@devon/hello-world`), but `devon` can't have two posts with that id
- [x] Remind the user about the fact this is a permalink
     - Warn them of the consequences if they change it
     - Maybe even maintain the original link?
- [ ] Because this impacts permalinks, be sure to add tests (perhaps even checking against prod) to confirm that permalinks are not broken from this point forward
- [ ] This should happen before "launch", because it will impact permalinks
